### ISSUE TITLE
Invalid signature of DrawTextureRec

### ISSUE THREAD

**Issue by mcjlnrtwcz** [foreignsasquatch/raylib-hx#24]
Hi! :wave:  It's my first day with haxe and raylib. I tried to draw an image and I had a problem with using `DrawTextureRec`. According to the [cheatsheet](https://www.raylib.com/cheatsheet/cheatsheet.html) the function should accept a vector and a rectangle, but the bindings say that it should be two rectangles.

Compare this

```
void DrawTextureEx(Texture2D texture, Vector2 position, float rotation, float scale, Color tint);  // Draw a Texture2D with extended parameters
```
to this
```
@:native("DrawTextureRec") static function DrawTextureRec(texture:Texture2D, source:Rectangle, dest:Rectangle, tint:Color):Void;
```

So it seems like there's a bug in the version available for haxe? :thinking:

Cheers!

**Comment by foreignsasquatch** [comment]
Are you using the latest git version? the code seems to be correct here: https://github.com/foreignsasquatch/raylib-hx/blob/main/source/Rl.cpp.hx#L1568 with the c raylib code https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1315

**Comment by foreignsasquatch** [comment]
Gonna close this
