### ISSUE TITLE
Vector2.create() generates broken code.

### ISSUE THREAD

**Issue by thepercentageguy** [foreignsasquatch/raylib-hx#25]
trying to do this

![image](https://user-images.githubusercontent.com/54141759/191729703-e912d752-c35f-4f7c-a6e5-395151d8db52.png)

generates this in the C++ file

![image](https://user-images.githubusercontent.com/54141759/191729760-691facf1-423d-4fde-aff5-ab41d318cad6.png)

Which triggers the following error when trying to compile
``error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax``

**Comment by foreignsasquatch** [comment]
Try just Rl.Vector2.create(x, y)

**Comment by thepercentageguy** [comment]
still broken

**Comment by foreignsasquatch** [comment]
could you share the code

**Comment by thepercentageguy** [comment]
> could you share the code

![image](https://user-images.githubusercontent.com/54141759/192086560-a6672967-0fd9-45e0-9102-e6925a9ea621.png)

**Comment by foreignsasquatch** [comment]
It would be nice if you could share a minimal example of this on a github repo.

**Comment by thepercentageguy** [comment]
> It would be nice if you could share a minimal example of this on a github repo.

https://github.com/hxray-engine/RayGen/blob/master/hxray/assets/RgSprite.hx#L57

**Comment by foreignsasquatch** [comment]
thank you. i will look into it when i have time
