### ISSUE TITLE
Update to 4.2

### ISSUE THREAD

**Issue by felipetesc** [foreignsasquatch/raylib-hx#26]
Hello! Can you update to the latest stable version ? And how can we help you to keep this project always updated?

**Comment by foreignsasquatch** [comment]
Hello. I will try to update to v4.2 when i have some free time which should be soon! As for helping, you can contribute by adding new functions, qol features or bug fixes.

Cheers

**Comment by foreignsasquatch** [comment]
Sorry, i've been busy with life and havent been able to update to 4.2. I'll maybe finish by the end of this year :sweat:

**Comment by felipetesc** [comment]
> Sorry, i've been busy with life and havent been able to update to 4.2. I'll maybe finish by the end of this year 😓

I'm glad to hear that!

**Comment by Akselmo** [comment]
Hey, seems someone else has made bindings for 4.2 here: https://github.com/rc-05/haxe-raylib

Maybe you can collaborate? I don't see the point of having three different raylib libraries for Haxe :sweat_smile:

**Comment by foreignsasquatch** [comment]
That would be nice. If @rc-05 is willing to then sure!

**Comment by rc-05** [comment]
Sorry for not responding earlier, sure we can merge the libraries so that we eliminate repetition

**Comment by Akselmo** [comment]
Awesome, should make things easier for everyone.

**Comment by foreignsasquatch** [comment]
A pr would be appreciated! (sorry for not replying early, im really busy with school currently :sweat:)

**Comment by rc-05** [comment]
> A pr would be appreciated! (sorry for not replying early, im really busy with school currently sweat)

PR done, check #34

**Comment by foreignsasquatch** [comment]
It should be version 4.2 rn i have modified and merge #34. if any functions are need and missing, feel free to make another issue. Closing this now
